"""change Time to Float

Revision ID: 3324c018f09d
Revises: f1a75f537556
Create Date: 2024-09-30 21:22:13.867239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3324c018f09d'
down_revision: Union[str, None] = 'f1a75f537556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'total_duration',
               existing_type=postgresql.TIME(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='EXTRACT(EPOCH FROM total_duration)'
               )
    op.alter_column('course_video', 'duration',
               existing_type=postgresql.TIME(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='EXTRACT(EPOCH FROM duration)'
               )
    op.alter_column('enrolled_course_video', 'timestamp',
               existing_type=postgresql.TIME(),
               type_=sa.Float(),
               existing_nullable=True,
                postgresql_using='EXTRACT(EPOCH FROM timestamp)'
               )
    op.alter_column('user', 'study_hours',
               existing_type=postgresql.TIME(),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='EXTRACT(EPOCH FROM study_hours)'
               )
    op.alter_column('user_progress', 'duration',
               existing_type=postgresql.TIME(),
               type_=sa.Float(),
               existing_nullable=True,
                postgresql_using='EXTRACT(EPOCH FROM duration)'
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_progress', 'duration',
               existing_type=sa.Float(),
               type_=postgresql.TIME(),
               existing_nullable=True,
               postgresql_using='to_timestamp(duration)'
               )
    op.alter_column('user', 'study_hours',
               existing_type=sa.Float(),
               type_=postgresql.TIME(),
               existing_nullable=True,
                postgresql_using='to_timestamp(study_hours)'
               )
    op.alter_column('enrolled_course_video', 'timestamp',
               existing_type=sa.Float(),
               type_=postgresql.TIME(),
               existing_nullable=True,
               postgresql_using='to_timestamp(timestamp)'
               )
    op.alter_column('course_video', 'duration',
               existing_type=sa.Float(),
               type_=postgresql.TIME(),
               existing_nullable=True,
               postgresql_using='to_timestamp(duration)'
               )
    op.alter_column('course', 'total_duration',
               existing_type=sa.Float(),
               type_=postgresql.TIME(),
               existing_nullable=True,
                postgresql_using='to_timestamp(total_duration)'
               )
    # ### end Alembic commands ###
