"""add enrolled course id to enrolled course video

Revision ID: bdd772b1d50c
Revises: 3e915a6b97ea
Create Date: 2024-10-08 01:51:40.954675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd772b1d50c'
down_revision: Union[str, None] = '3e915a6b97ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrolled_course_video', sa.Column('enrolled_course_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'enrolled_course_video', 'enrolled_course', ['enrolled_course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrolled_course_video', type_='foreignkey')
    op.drop_column('enrolled_course_video', 'enrolled_course_id')
    # ### end Alembic commands ###
