"""add duration to course_video

Revision ID: ec2693deb94d
Revises: 1bbc4f23ea38
Create Date: 2024-09-27 23:41:18.658175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2693deb94d'
down_revision: Union[str, None] = '1bbc4f23ea38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('course_video', sa.Column('duration', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_video', 'duration')
    # ### end Alembic commands ###
