"""adding field chapter to each video course

Revision ID: 20b58e263a8d
Revises: bdd772b1d50c
Create Date: 2024-10-09 16:17:01.051085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20b58e263a8d"
down_revision: Union[str, None] = "bdd772b1d50c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course_video", sa.Column("chapter", sa.Integer(), nullable=True))
    op.add_column(
        "course_video", sa.Column("video_description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course_video", "video_description")
    op.drop_column("course_video", "chapter")
    # ### end Alembic commands ###
