"""adjust achievement&user model

Revision ID: 56db77c40372
Revises: 9e64a18dc752
Create Date: 2024-11-12 00:25:10.130651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56db77c40372"
down_revision: Union[str, None] = "9e64a18dc752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("achievement_course_id_fkey", "achievement", type_="foreignkey")
    op.drop_constraint("achievement_user_id_fkey", "achievement", type_="foreignkey")
    op.drop_column("achievement", "received_at")
    op.drop_column("achievement", "course_id")
    op.drop_column("achievement", "user_id")
    op.add_column("user", sa.Column("achievements", sa.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "achievements")
    op.add_column(
        "achievement",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "achievement",
        sa.Column("course_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "achievement",
        sa.Column("received_at", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "achievement_user_id_fkey", "achievement", "user", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "achievement_course_id_fkey", "achievement", "course", ["course_id"], ["id"]
    )
    # ### end Alembic commands ###
