"""change category_list instead category_id

Revision ID: f1a75f537556
Revises: ec2693deb94d
Create Date: 2024-09-30 13:35:29.720612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a75f537556'
down_revision: Union[str, None] = 'ec2693deb94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('category_list', sa.ARRAY(sa.String()), nullable=True))
    op.drop_constraint('course_category_id_fkey', 'course', type_='foreignkey')
    op.drop_column('course', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('course_category_id_fkey', 'course', 'category', ['category_id'], ['id'])
    op.drop_column('course', 'category_list')
    # ### end Alembic commands ###
